export const geodb = [
  {
    id: 1,
    titulo: 'Perú - Límite Internacional',
    descripcion: 'Límite nacional del Perú, frontera con Ecuador, Colombia, Brasil, Bolivia, Chile y Océano Pacífico.',
    fuente: 'INEI 2022',
    keyword: ['peru', 'limite', 'frontera', 'boundaries', 'internacional', 'politico', 'ign', 'inei'],
    categoria: 'Geopolitica',
    img: '#/../..',
    cosulta: '#',
    visualiza: '#',
    descarga: {shp: '#', kml: '#', geojson: '#', gml: '#', csv: '#'},
  },
  {
    id: 2,
    titulo: 'Perú - Límites Departamentales',
    descripcion: 'Límites departamentales del Perú. ',
    fuente: '',
    keyword: ['peru', 'limite', 'departamentos', 'lima', 'departamental', 'regiones', 'regional'],
    categoria: 'Geopolitica',
    img: '#/../..',
    cosulta: '#',
    visualiza: '#',
    descarga: {shp: '#', kml: '#', geojson: '#', gml: '#', csv: '#'},
  },
  {
    id: 3,
    titulo: 'Perú - Límites Distritales',
    descripcion: 'Límites distritales del Perú. ',
    fuente: '',
    keyword: ['peru', 'limite', 'distrital', 'lima', 'distritos', 'distrito', 'municipalidad', 'municipios'],
    categoria: 'Geopolitica',
    img: '#/../..',
    cosulta: '#',
    visualiza: '#',
    descarga: {shp: '#', kml: '#', geojson: '#', gml: '#', csv: '#'},
  },
  {
    id: 4,
    titulo: 'Perú - Límites Provinciales',
    descripcion: 'Límites provinciales del Perú.',
    fuente: '',
    keyword: ['peru', 'limite', 'provincial', 'provincias', 'provincia', 'region', 'regionales'],
    categoria: 'Geopolitica',
    img: '#/../..',
    cosulta: '#',
    visualiza: '#',
    descarga: {shp: '#', kml: '#', geojson: '#', gml: '#', csv: '#'},
  },
  {
    id: 5,
    titulo: 'Perú - Red Hidrográfica Nacional',
    descripcion: 'Red hidrográfica nacional, ríos, lagos, lagunas, etc.',
    fuente: '',
    keyword: ['peru', 'red', 'rios', 'agua', 'hidrografica', 'hidrografia', 'lagos', 'lagunas', 'cuenca',],
    categoria: 'Hidrografia',
    img: '#/../..',
    cosulta: '#',
    visualiza: '#',
    descarga: {shp: '#', kml: '#', geojson: '#', gml: '#', csv: '#'},
  },
]