export const geodb = [
  {
    id: 1,
    titulo: 'Perú - Límite Nacional',
    descripcion: 'Límite nacional del Perú, frontera con Ecuador, Colombia, Brasil, Bolivia y Chile.',
    keyword: ['peru', 'limite', 'frontera', 'boundaries', 'internacional', 'politico'],
    categoria: 'Geopolitica',
    img: '#/../..',
    cosulta: '#',
    visualiza: '#',
    descarga: {shp: '#', kml: '#', geojson: '#', gml: '#', csv: '#'},
  },
  {
    id: 2,
    titulo: 'Perú - Límites Departamentales',
    descripcion: 'Límites departamentales del Perú. ',
    keyword: ['peru', 'limite', 'departamentos', 'lima', 'departamental', 'regiones', 'regional'],
    categoria: 'Geopolitica',
    img: '#/../..',
    cosulta: '#',
    visualiza: '#',
    descarga: {shp: '#', kml: '#', geojson: '#', gml: '#', csv: '#'},
  },
  {
    id: 3,
    titulo: 'Perú - Límites Distritales',
    descripcion: 'Límites distritales del Perú. ',
    keyword: ['peru', 'limite', 'distrital', 'lima', 'distritos', 'distrito', 'municipalidad', 'municipios'],
    categoria: 'Geopolitica',
    img: '#/../..',
    cosulta: '#',
    visualiza: '#',
    descarga: {shp: '#', kml: '#', geojson: '#', gml: '#', csv: '#'},
  },
]